### ISSUE TITLE
"Tag" like option for bullet points

### ISSUE THREAD

**Issue by BryanQuigley** [notsag/yaml-resume#18]
**Is your feature request related to a problem? Please describe.**
One can go for many different kinds of jobs and it's advantageous to adapt your resume to each one.  As it stands today, that is a manual process.   One way to do this is to have a longer resume you never submit and then go through and remove bullets that are not relevant to that job.

**Describe the solution you'd like**
I'd like a way to "tag" bullet points so that they can be easier to filter. 

The first iteration I came up with is:
experiences:
- company: Foo company
  position: Senior Python Developer
  start_date: January 2018
  summary:  Developer for the main Foo webapp
  bullets:
    ? Worked on migration from python 2.7 to 3.6
    : [python3, py2to3]
    ? Scrum master for the team of 8 people
    : [scrum, leadership]
    ? Added automated unit tests
    : [CI, testing, pytest]
  website: https://foo.com
....

**Describe alternatives you've considered**
We could also use references, but that would break the flow of the resume from a person editing by hand.

**Additional context**
I'm hoping to use this as the basis for a potentially paid (but obviously under terms of GPLv3) service.  
I fully intend to implement this and open a PR but want to discuss first.

**Comment by notsag** [comment]
I really like the idea of optional items for a job, feel free to implement this and propose a PR.
Unfortunately I was not very involved with this project for the past year but I'm hoping to continue working on it so your work would be much appreciated.

**Comment by BryanQuigley** [comment]
I no longer intend to implement it..  sorry for the noise :/
