### ISSUE TITLE
CV passes validation but fails at export

### ISSUE THREAD

**Issue by xsa** [notsag/yaml-resume#22]
**Describe the bug**
CV passes the validation step but fails at export if the skills level is not set.

**To Reproduce**
1. Manually create .yml file following the schema
2. Omit the skills level property
3. Export the .yml file to PDF

**Expected behavior**
If the .yml file passes validation, I expect it to not fail at export. Can make skills level optional as it's sometimes hard to quantify.

**Desktop (please complete the following information):**
 - OS: Mac OS X 
 - Version 11.2.3
 - Python Version 3.9.2

**Comment by notsag** [comment]
@xsa Thank you for reporting this bug, I"ll have a look at this.
